In [1]:
print("hello")

hello

In [2]:
import requests
import pandas as pd
import json
from bs4 import BeautifulSoup

In [3]:
url = 'https://finance.naver.com/sise/sise_group.nhn?type=upjong'

In [4]:
r = requests.get(url)

In [5]:
bs = BeautifulSoup(r.text, 'html.parser')

In [6]:
# upjong = bs.find(class_ = 'type_1').find_all("tr")
# # 오류남 왜?? --> table tag가 있어야 pandas가 인식

In [7]:
upjong = bs.find("table", class_ = 'type_1')

In [8]:
type(upjong)

bs4.element.Tag

In [9]:
upjong_df = pd.read_html(str(upjong))[0]

In [10]:
upjong_df

          업종별 시세명    전일대비 전일대비 등락현황                  등락그래프
          업종별 시세명    전일대비        전체    상승   보합    하락 등락그래프
0             해운사  +2.90%       7.0   5.0  1.0   1.0  100%
1         도로와철도운송  +2.18%       6.0   3.0  1.0   2.0   75%
2      양방향미디어와서비스  +1.71%      10.0   5.0  2.0   3.0   58%
3            통신장비  +1.66%      46.0  21.0  9.0  16.0   57%
4        레저용장비와제품  +1.47%       9.0   6.0  1.0   2.0   50%
..            ...     ...       ...   ...  ...   ...   ...
121    생명과학도구및서비스  -1.48%      25.0   5.0  2.0  18.0   51%
122           문구류  -1.82%       3.0   0.0  1.0   2.0   62%
123  독립전력생산및에너지거래  -1.85%       1.0   0.0  0.0   1.0   63%
124           NaN     NaN       NaN   NaN  NaN   NaN   NaN
125           NaN     NaN       NaN   NaN  NaN   NaN   NaN

[126 rows x 7 columns]

In [11]:
upjong_df = upjong_df.dropna()

In [12]:
upjong_df

          업종별 시세명    전일대비 전일대비 등락현황                  등락그래프
          업종별 시세명    전일대비        전체    상승   보합    하락 등락그래프
0             해운사  +2.90%       7.0   5.0  1.0   1.0  100%
1         도로와철도운송  +2.18%       6.0   3.0  1.0   2.0   75%
2      양방향미디어와서비스  +1.71%      10.0   5.0  2.0   3.0   58%
3            통신장비  +1.66%      46.0  21.0  9.0  16.0   57%
4        레저용장비와제품  +1.47%       9.0   6.0  1.0   2.0   50%
..            ...     ...       ...   ...  ...   ...   ...
116        전기유틸리티  -1.38%       4.0   1.0  0.0   3.0   47%
120     에너지장비및서비스  -1.44%      10.0   2.0  3.0   5.0   49%
121    생명과학도구및서비스  -1.48%      25.0   5.0  2.0  18.0   51%
122           문구류  -1.82%       3.0   0.0  1.0   2.0   62%
123  독립전력생산및에너지거래  -1.85%       1.0   0.0  0.0   1.0   63%

[79 rows x 7 columns]

In [13]:
upjong_df.columns

MultiIndex([(  '업종별 시세명', '업종별 시세명'),
            (     '전일대비',    '전일대비'),
            ('전일대비 등락현황',      '전체'),
            ('전일대비 등락현황',      '상승'),
            ('전일대비 등락현황',      '보합'),
            ('전일대비 등락현황',      '하락'),
            (    '등락그래프',   '등락그래프')],
           )

## 콜롬에 값이 두줄에서 columns.droplevel을 이용해 한줄제거

In [14]:
upjong_df.columns = upjong_df.columns.droplevel(0)

In [15]:
upjong_df

          업종별 시세명    전일대비    전체    상승   보합    하락 등락그래프
0             해운사  +2.90%   7.0   5.0  1.0   1.0  100%
1         도로와철도운송  +2.18%   6.0   3.0  1.0   2.0   75%
2      양방향미디어와서비스  +1.71%  10.0   5.0  2.0   3.0   58%
3            통신장비  +1.66%  46.0  21.0  9.0  16.0   57%
4        레저용장비와제품  +1.47%   9.0   6.0  1.0   2.0   50%
..            ...     ...   ...   ...  ...   ...   ...
116        전기유틸리티  -1.38%   4.0   1.0  0.0   3.0   47%
120     에너지장비및서비스  -1.44%  10.0   2.0  3.0   5.0   49%
121    생명과학도구및서비스  -1.48%  25.0   5.0  2.0  18.0   51%
122           문구류  -1.82%   3.0   0.0  1.0   2.0   62%
123  독립전력생산및에너지거래  -1.85%   1.0   0.0  0.0   1.0   63%

[79 rows x 7 columns]

# 상승 종목

In [16]:
base_url = "https://finance.naver.com/sise/field_submit.nhn?"

In [20]:
url = "https://finance.naver.com/sise/sise_rise.nhn"

In [21]:
r = requests.get(url)

In [ ]:
bs = BeautifulSoup(r.text, 'lxml')