In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
import sqlite3
import re

In [3]:
requests.get('https://finance.naver.com/item/sise_day.nhn?code=005930&page=4').text

'\n\n\n\n\n\n\n<html lang="ko">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">\n<title>네이버 금융</title>\n<link rel="stylesheet" type="text/css" href="/css/newstock.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/common.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/layout.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/main.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/newstock2.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/newstock3.css?20191212151800">\n<link rel="stylesheet" type="text/css" href="/css/world.css?20191212151800">\n</head>\n<body>\n<script language="JavaScript">\nfunction mouseOver(obj){\n  obj.style.backgroundColor="#f6f4e5";\n}\nfunction mouseOut(obj){\n  obj.style.backgroundColor="#ffffff";\n}\n</script>\n\t\t\t\t<h4 class="tlline2"><strong><span class="red03">일별</span>시세</strong></h4>\t\t\t\n\t\t\t\t<table cellspacing="0" class="type2">\n\t\t\t\t<tr>\n\t\t\t\t<th>날짜</th>\n\t\t\t\t<th>종가</th>\n\t\t\t\t<th>전일비</th>\n\t\t\t\t<th>시가</th>\n\t\t\t\t<th>고가</th>\n\t\t\t\t<th>저가</th>\n\t\t\t\t<th>거래량</th>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t<td colspan="7" height="8"></td>\n\t\t\t\t</tr>\n\n\n\t\n\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.08</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,100</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n\t\t\t\t800\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,200</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,300</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,000</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">11,603,290</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.07</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,900</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n\t\t\t\t400\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">9,257,116</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.06</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,300</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t600\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,900</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">53,500</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">14,361,133</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.05</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,700</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t400\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,100</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">10,581,034</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.04</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,300</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t1,100\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">52,300</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">13,012,411</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t<td colspan="7" height="8"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t<td colspan="7" height="1" bgcolor="#e1e1e1"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t<td colspan="7" height="8"></td>\n\t\t\t\t</tr>\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.11.01</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,200</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t800\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,600</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,200</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">8,467,846</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.10.31</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,400</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<span class="tah p11">0</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,000</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,300</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">10,304,777</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.10.30</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,400</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n\t\t\t\t700\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,800</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,200</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">8,959,435</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.10.29</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,100</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n\t\t\t\t200\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,400</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,800</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">7,581,629</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t\n\t\t\t\t\t<tr onMouseOver="mouseOver(this)" onMouseOut="mouseOut(this)">\n\t\t\t\t\t<td align="center"><span class="tah p10 gray03">2019.10.28</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,300</span></td>\n\t\t\t\t\t<td class="num">\n\t\t\t\t<img src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span class="tah p11 red02">\n\t\t\t\t400\n\t\t\t\t</span>\n\t\t\t</td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">51,500</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">50,700</span></td>\n\t\t\t\t\t<td class="num"><span class="tah p11">6,431,522</span></td>\n\t\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\t\t\n\t\n\t\t\n\t\n\n\t\t\t\t<tr>\n\t\t\t\t<td colspan="7" height="8"></td>\n\t\t\t\t</tr>\n\t\t\t\t</table>\n\t\t\t\t<!--- 페이지 네비게이션 시작--->\n\t\t\t\t<table summary="페이지 네비게이션 리스트" class="Nnavi" align="center">\n\t\t\t\t<caption>페이지 네비게이션</caption>\n\t\t\t\t<tr>\t\t\n\t\t\t\n\t\t\t\t<td class="pgLL">\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=1"  >\n\t\t\t\t<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarLL.gif" width="7" height="5" alt="">맨앞\n\t\t\t\t</a>\n\t\t\t\t</td>\n\n                \n                <td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=1"  >1</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=2"  >2</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=3"  >3</a>\n\t\t\t\t</td>\n<td class="on">\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=4"  >4</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=5"  >5</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=6"  >6</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=7"  >7</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=8"  >8</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=9"  >9</a>\n\t\t\t\t</td>\n<td>\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=10"  >10</a>\n\t\t\t\t</td>\n\n                <td class="pgR">\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=11"  >\n\t\t\t\t다음<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3" height="5" alt="" border="0">\n\t\t\t\t</a>\n\t\t\t\t</td>\n\n                <td class="pgRR">\n\t\t\t\t<a href="/item/sise_day.nhn?code=005930&amp;page=591"  >맨뒤\n\t\t\t\t<img src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8" height="5" alt="" border="0">\n\t\t\t\t</a>\n\t\t\t\t</td>\n\n            \n\t\t\t\t</tr>\n\t\t\t\t</table>\n\t\t\t\t<!--- 페이지 네비게이션 끝--->\n\n\n\t<script type="text/javascript" src="/js/jindo.min.ns.1.5.3.euckr.js?20191212151800"></script>\n\t<script type="text/javascript" src="/js/lcslog.js?20191212151800"></script>\n\t<script type="text/javascript">\n        ;(function(){\n            var eventType = "onpageshow" in window ? "pageshow" : "load";\n            jindo.$Fn(function(){\n                lcs_do();\n            }).attach(window, eventType);\n        })();\n\t</script>\n\n</body>'

In [5]:
len(pd.read_html('https://finance.naver.com/item/sise_day.nhn?code=005930&page=2'))

2

In [7]:
pd.read_html('https://finance.naver.com/item/sise_day.nhn?code=005930&page=2')[0]

            날짜       종가     전일비       시가       고가       저가         거래량
0          NaN      NaN     NaN      NaN      NaN      NaN         NaN
1   2019.12.06  50400.0   900.0  50100.0  50900.0  49950.0  11414563.0
2   2019.12.05  49500.0    50.0  50200.0  50400.0  49500.0  10449715.0
3   2019.12.04  49450.0   450.0  49600.0  49850.0  49000.0  13246549.0
4   2019.12.03  49900.0   500.0  49800.0  50300.0  49500.0  12059812.0
5   2019.12.02  50400.0   100.0  50900.0  51300.0  50400.0  18877252.0
6          NaN      NaN     NaN      NaN      NaN      NaN         NaN
7          NaN      NaN     NaN      NaN      NaN      NaN         NaN
8          NaN      NaN     NaN      NaN      NaN      NaN         NaN
9   2019.11.29  50300.0  1000.0  51200.0  51400.0  50200.0  11179334.0
10  2019.11.28  51300.0   900.0  51900.0  52100.0  51300.0   6833885.0
11  2019.11.27  52200.0   400.0  51800.0  52300.0  51600.0   7546261.0
12  2019.11.26  51800.0     0.0  51900.0  52900.0  51800.0  27372226.0
13  2019.11.25  51800.0   200.0  52200.0  52600.0  51700.0   9050625.0
14         NaN      NaN     NaN      NaN      NaN      NaN         NaN

In [8]:
pd.read_html('https://finance.naver.com/item/sise_day.nhn?code=005930&page=2')[1]

   0   1   2   3   4   5   6   7   8   9   10  11  12
0  맨앞   1   2   3   4   5   6   7   8   9  10  다음  맨뒤

In [9]:
data = pd.read_html('https://finance.naver.com/item/sise_day.nhn?code=005930&page=2')[0].dropna()

In [10]:
data

            날짜       종가     전일비       시가       고가       저가         거래량
1   2019.12.06  50400.0   900.0  50100.0  50900.0  49950.0  11414563.0
2   2019.12.05  49500.0    50.0  50200.0  50400.0  49500.0  10449715.0
3   2019.12.04  49450.0   450.0  49600.0  49850.0  49000.0  13246549.0
4   2019.12.03  49900.0   500.0  49800.0  50300.0  49500.0  12059812.0
5   2019.12.02  50400.0   100.0  50900.0  51300.0  50400.0  18877252.0
9   2019.11.29  50300.0  1000.0  51200.0  51400.0  50200.0  11179334.0
10  2019.11.28  51300.0   900.0  51900.0  52100.0  51300.0   6833885.0
11  2019.11.27  52200.0   400.0  51800.0  52300.0  51600.0   7546261.0
12  2019.11.26  51800.0     0.0  51900.0  52900.0  51800.0  27372226.0
13  2019.11.25  51800.0   200.0  52200.0  52600.0  51700.0   9050625.0

# USE Sqlite3

In [11]:
con = sqlite3.connect("./common_stock.db")

In [12]:
cur = con.cursor()